edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
format_code_in_doc_comments = true
normalize_doc_attributes = true
merge_derives = true
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"
